# Generated by Django 4.2.7 on 2025-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Developer's full name", max_length=100)),
                ('student_id', models.CharField(blank=True, help_text='Student ID or identifier', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography or description')),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Profile',
                'verbose_name_plural': 'Developer Profiles',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the section', max_length=200)),
                ('content', models.TextField(help_text='Main content of the section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this section is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this section was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this section was last updated')),
            ],
            options={
                'verbose_name': 'Content Section',
                'verbose_name_plural': 'Content Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
