# Generated by Django 4.2.7 on 2025-01-20

from django.db import migrations


def add_developer_data(apps, schema_editor):
    DeveloperProfile = apps.get_model('developer_info', 'DeveloperProfile')
    Section = apps.get_model('developer_info', 'Section')
    
    # 添加开发者信息
    developer = DeveloperProfile.objects.create(
        name="陈奕鸣",
        student_id="20231201023",
        bio="全栈开发工程师，热爱编程和技术创新",
        email="chenyiming@example.com",
        github_url="https://github.com/chenyiming",
        linkedin_url="https://linkedin.com/in/chenyiming"
    )
    
    # 添加示例章节内容
    sections_data = [
        {
            'title': '个人简介',
            'content': '我是一名热爱技术的全栈开发工程师，专注于Web开发和人工智能领域。',
            'is_active': True
        },
        {
            'title': '技术栈',
            'content': '熟练掌握Python, Django, JavaScript, React, Vue.js, MySQL, MongoDB等技术。',
            'is_active': True
        },
        {
            'title': '项目经验',
            'content': '参与过多个Web应用开发项目，包括电商平台、内容管理系统和数据分析工具。',
            'is_active': True
        }
    ]
    
    for section_data in sections_data:
        Section.objects.create(**section_data)


def remove_developer_data(apps, schema_editor):
    DeveloperProfile = apps.get_model('developer_info', 'DeveloperProfile')
    Section = apps.get_model('developer_info', 'Section')
    
    # 删除添加的数据
    DeveloperProfile.objects.filter(student_id="20231201023").delete()
    Section.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('developer_info', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_developer_data, remove_developer_data),
    ]